--- 
- hosts: myservers
  become: yes
  tasks: 
    - name: Installing apache
      apt: name=apache2 update_cache=yes state=latest


    - name: Start the Apache Service
       service: 
         name: httpd
         state: restarted    

     - name: Putting Index page
       copy: 
         content: "Welcome to the Automation"
         dest: /var/www/html/index.html

     - name: Firewall Service Restarting
       service: 
         name: firewalld
         state: restarted

     - name: Firewall access allocation
       firewalld: 
         port: 80/tcp
         permanent: true
         state: enabled  

  handlers:
    - name: "restart apache2"
      service: "name=apache2 state=restarted"
