---
- name: Playbook for apache server on Ubnutu
  hosts: myservers
  become: yes    # run as root

  tasks: 
    - name: Install apache2
      apt: name=apache2 state=present 

    - name: Start apache2 service
      service: name=apache2 state=started enabled=yes

    - name: Upgrade all apt packages
      apt: upgrade=dist force_apt_get=yes

    - name: Install git
      apt: name=git 

    - name: Clone git repo
      git: repo=https://github.com/jcfoster02/basic-website.git dest=/var/www/html
