--- 

- 

  become: true

  hosts: myservers

  tasks: 

    - 

      apt: "name=apache2 update_cache=yes state=latest"

      name: "install apache2"

    - 

      apache2_module: "name=rewrite state=present"

      name: "enabled mod_rewrite"

      notify: 

        - "restart apache2"

- 

  action: "apt pkg='{{ item }}' state=installed"

  name: "Install MySQL"

  with_items: 

    - libmysqlclient-dev

    - python-mysqldb

    - mysql-server

    - mysql-client

- 

  action: "service name=mysql state=started"

  name: "Start the MySQL service"

- 

  mysql_db: "name=test state=absent"

  name: "Remove the test database"

- 

  mysql_user: "user=”deploy” host=”%” password=password priv=*.*:ALL,GRANT"

  name: "Create deploy user for mysql"

- 

  mysql_user: "user=’’ host={{ item }} state=absent"

  name: "Ensure anonymous users are not in the database"

  with_items: 

    - "127.0.0.1"

    - ":1"

    - localhost

- 

  mysql_user: "name=root host={{ item }} password=password"

  name: "Update mysql root password for all root accounts"

  with_items: 

    - "127.0.0.1"

    - ":1"

    - localhost

- 

  apt: name=python-minimal

  name: "Install Python"
