---
- name: Install Maven on Ubuntu server
  hosts: myservers
  become: yes
  tasks:
    - name: Installing Maven
      apt: name=maven state=present update_cache=yes   # apt-get update
      tags: install_mvn
